// authentication
export const REQUEST_AUTH_SUCCESS  = 'REQUEST_AUTH_SUCCESS';
export const REQUEST_AUTH_FAILURE = 'REQUEST_AUTH_FAILURE';

// categories
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
